# generated by datamodel-codegen:
#   filename:  api.yml
#   timestamp: 2024-06-20T02:13:44+00:00

from __future__ import annotations

from enum import Enum

from typing import Annotated
from pydantic import BaseModel, Field, ConfigDict


class OCCUPATION(str, Enum):
    SELF_EMP = 'SELF-EMP'
    SAL = 'SAL'
    PROF = 'PROF'
    SENP = 'SENP'


class ACCTYPE(str, Enum):
    SA = 'SA'
    CA = 'CA'


class Lead(BaseModel):
    model_config = ConfigDict(use_enum_values=True)    # Necessary to convert back to dict correctly.
    
    BALANCE: Annotated[float, Field(strict=True, ge=0.0)]
    OCCUPATION: OCCUPATION
    SCR: Annotated[float, Field(strict=True, ge=100.00, le=999.00)]
    HOLDING_PERIOD: Annotated[float, Field(strict=True, ge=0.0)]
    ACC_TYPE: ACCTYPE
    LEN_OF_RLTN_IN_MNTH: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_L_CR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_L_DR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_BR_CSH_WDL_DR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_ATM_DR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_NET_DR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_MOB_DR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_CHQ_DR_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    FLG_HAS_CC: Annotated[int, Field(strict=True, ge=0, le=1)]
    AMT_ATM_DR: Annotated[float, Field(strict=True, ge=0.0)]
    AMT_BR_CSH_WDL_DR: Annotated[float, Field(strict=True, ge=0.0)]
    AMT_CHQ_DR: Annotated[float, Field(strict=True, ge=0.0)]
    AMT_NET_DR: Annotated[float, Field(strict=True, ge=0.0)]
    AMT_MOB_DR: Annotated[float, Field(strict=True, ge=0.0)]
    AMT_L_DR: Annotated[float, Field(strict=True, ge=0.0)]
    FLG_HAS_ANY_CHGS: Annotated[int, Field(strict=True, ge=0, le=1)]
    AMT_OTH_BK_ATM_USG_CHGS: Annotated[float, Field(strict=True, ge=0.0)]
    AMT_MIN_BAL_NMC_CHGS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_IW_CHQ_BNC_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    NO_OF_OW_CHQ_BNC_TXNS: Annotated[float, Field(strict=True, ge=0.0)]
    AVG_AMT_PER_ATM_TXN: Annotated[float, Field(strict=True, ge=0.0)]
    AVG_AMT_PER_CSH_WDL_TXN: Annotated[float, Field(strict=True, ge=0.0)]
    AVG_AMT_PER_CHQ_TXN: Annotated[float, Field(strict=True, ge=0.0)]
    AVG_AMT_PER_NET_TXN: Annotated[float, Field(strict=True, ge=0.0)]
    AVG_AMT_PER_MOB_TXN: Annotated[float, Field(strict=True, ge=0.0)]
    FLG_HAS_NOMINEE: Annotated[int, Field(strict=True, ge=0, le=1)]
    FLG_HAS_OLD_LOAN: Annotated[int, Field(strict=True, ge=0, le=1)]


class Prediction(BaseModel):
    predict_flag: Annotated[int, Field(strict=True, ge=0, le=1)]
    probability: Annotated[float, Field(strict=True, ge=0, le=1)]